language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm build
deploy:
  provider: script
  script: npm run deploy-prod
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - ENCRYPTION_LABEL: "bc7a18e02161"
  - COMMIT_AUTHOR_EMAIL: "poloagustin@gmail.com"
  - TARGET_REPO_STAGING: https://github.com/kraneos/gg-app-staging.git
  - SSH_TARGET_REPO_STAGING: git@github.com:kraneos/gg-app-staging.git
