language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm build
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
    branch: staging
