language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm build
deploy:
  provider: script
  script: bash -x deploy.sh
  skip_cleanup: true
  on:
    branch: master
    branch: staging
env:
  global:
  - ENCRYPTION_LABEL: "bc7a18e02161"
  - COMMIT_AUTHOR_EMAIL: "poloagustin@gmail.com"
